### ISSUE TITLE
Adapter le plugin pour etre utilisé avec Polylang

### ISSUE THREAD

**Issue by SilverCelyan** [Celyan-SAS/CSV-to-WordPress-content-importer#3]
- [x] Récupérer les langues configurées et proposer l'association acf/col par langues
- [x] Enregistrer l'association
- [x] Enregistrer un post par langue en utilisant l'assoc
- [x] Détécter que polylang est utilisé (par sécurité) et utiliser une autre methode de stokage de l'assoc si il est absent

**Comment by SilverCelyan** [comment]
La version commit a l'heure ou j'écris ce message a la fonctionnalité avec ou sans polylang

**Comment by yannbug** [comment]
top!
